cargo-features = ["edition"]

[package]
name = "peri-lang"
version = "0.1.0"
authors = ["Alexis Hunt <alercah@gmail.com>"]
edition = '2018'

[build-dependencies]
lalrpop = "0.15.2"

[dependencies]
failure = "0.1.1"
num-rational = "0.2.1"
lalrpop-util = "0.15.2"
